---
title: "GWAS2023analysis"
author: "Venkata Naresh Boddepalli"
date: "2023-12-24"
output:
  word_document: default
  html_document: default
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
#install.packages("mvtnorm")

library(inti)
library(lme4)
library(GAPIT)

```

#GAPIT starts 
```{r}

#setwd("C:\\Users\\naresh89\\Desktop\\My projects\\GWAS\\Analysis_2024\\BLINK_MLM")
myY <- read.table("C:\\Users\\naresh89\\Desktop\\My projects\\gwas\\Seed image analysis\\blups\\blups.csv _phenotype.txt", head = TRUE)
myG <- read.table("C:\\Users\\naresh89\\Desktop\\My projects\\gwas\\Seed image analysis\\blups\\blups.csv _genotype.hmp.txt", comment.char = "")

#myG <- read.table("mdp_genotype_test.hmp.txt", head = FALSE)
myGAPIT <- GAPIT(G=myG, output.numerical=TRUE)
myGD= myGAPIT$GD
myGM= myGAPIT$GM


#myGD=read.table("C:\\Users\\naresh89\\Desktop\\My projects\\GWAS\\Analysis_2024\\2023\\GAPIT.Genotype.Numerical.txt",head=T)
#myGM=read.table("C:\\Users\\naresh89\\Desktop\\My projects\\GWAS\\Analysis_2024\\2023\\GAPIT.Genotype.map.txt",head=T)
#Step 2: Run GAPIT
#setwd("C:\\Users\\naresh89\\Desktop\\My projects\\GWAS\\Analysis_2024\\2023\\BLINK_farmCPU")
myGAPIT <- GAPIT(
  Y=myY,
  GD=myGD,
  GM=myGM,
  PCA.total=3,
  SNP.MAF = 0.05,
  Multiple_analysis = TRUE,
  model=c("BLINK", "MLM", "farmCPU")
  )
```

`
